# Mainly for testing standalone version of the site.
# Going to just a component in mult-repo docsite in the future.

site:
  title: BeagleBoard Documentation
  start_page: home::index.adoc

content:
  sources:
  - url: .
    start_paths: home
    branches: HEAD

  - url: https://github.com/beagleboard/bb-imager-rs.git
    start_paths: docs
    tags: [0.0.19]
    branches: ~

  - url: https://github.com/beagleboard/greybus-zephyr.git
    start_paths: docs
    branches: HEAD

  - url: https://github.com/beagleboard/PocketBeagle-2-Docs.git
    branches: 
      - "A0"
      - "A1"

ui:
  bundle:
    url: https://github.com/beagleboard/antora-ui-beagle/releases/download/continuous-release/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

antora:
  extensions:
  - '@antora/pdf-extension'
  - '@antora/lunr-extension'
