# Mainly for testing standalone version of the site.
# Going to just a component in mult-repo docsite in the future.

site:
  title: BeagleBoard Imaging Utility
  start_page: home::index.adoc

content:
  sources:
  - url: .
    start_paths: home
    branches: HEAD

  - url: https://github.com/beagleboard/bb-imager-rs.git
    start_paths: docs
    tags: [0.0.18]
    branches: ~
    # branches: HEAD

  - url: https://github.com/beagleboard/greybus-zephyr.git
    start_paths: docs
    branches: HEAD

ui:
  bundle:
    url: https://github.com/beagleboard/antora-ui-beagle/releases/download/continuous-release/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

antora:
  extensions:
  - '@antora/pdf-extension'
